#!/bin/bash
#
<<<<<<<< HEAD:ymls/cron.yml
# Title:      PGBlitz (Reference Title File)
# Authors:    Admin9705, Deiteq, and many PGBlitz Contributors
# URL:        https://pgblitz.com - http://github.pgblitz.com
# GNU:        General Public License v3.0
################################################################################
---
- cron:
    name: Daily log cleaner
    special_time: 'daily'
    job: 'tlogs'
    state: present
========
# Title:      Reference Title File - PGBlitz
# Author(s):  Admin9705 & https://github.com/PGBlitz/PGClone/graphs/contributors & Deiteq
# URL:        https://pgblitz.com - http://github.pgblitz.com
# GNU:        General Public License v3.0
################################################################################
sudo systemctl status sd
>>>>>>>> ba72cca3f19b78e8913b8ea0e801932c5efe6965:templates/status-sd
